# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senti', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='firstname',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='lastname',
            new_name='Fullname',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='username',
            new_name='Username',
        ),
    ]
