# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-06 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senti', '0003_auto_20190628_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=30)),
                ('reviewtypes', models.CharField(max_length=30)),
            ],
        ),
    ]
