# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senti', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
